CREATE TABLE data (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  description VARCHAR(300),
  done BOOLEAN NOT NULL DEFAULT 0,
  createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(40) NOT NULL,
  password VARCHAR(40) NOT NULL,
  account_type VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO
  auth (username, password, account_type)
VALUES
  ('ejemplo', MD5('mypassword'), 'admin'),
  ('ejemplo', MD5('mypassword'), 'user');

show tables;

select
  *
from
  auth;

  SELECT * FROM palaciodb.CatalogoCtasEGR;

BULK INSERT palaciodb.CatalogoCtasEGR
FROM 'C:\Users\hecto\OneDrive\Documentos\Libro1.csv'
WITH
(
  ROWTERMINATOR = '\n',
  FIELDTERMINATOR = ','
)

LOAD DATA INFILE 'C:\Users\hecto\OneDrive\Documentos\Libro1.csv'
INTO TABLE palaciodb.CatalogoCtasEGR
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

CREATE TABLE CatalogoCtasEGR (
  id INT NOT NULL AUTO_INCREMENT,
  REVISADO BOOLEAN DEFAULT 0,
  BENEFICIARIO VARCHAR(50),
  TIPO_DE_PERSONA VARCHAR(20),
  RFC VARCHAR(15),
  CURP VARCHAR(20),
  CATALOGO_VIALIDAD VARCHAR(30),
  TIPO_DE_VIALIDAD VARCHAR(30),
  NOMBRE_DE_VIALIDAD VARCHAR(50),
  NUMERO_INT_EXT_MZ_LT VARCHAR(15),
  ASENTAMIENTO VARCHAR(25),
  NOMBRE_DEL_ASENTAMIENTO VARCHAR(25),
  ENTIDAD_FEDERATIVA VARCHAR(40),
  MUNICIPIO_DELEGACION VARCHAR(40),
  CODIGO_POSTAL VARCHAR(30),
  BANCO VARCHAR(30),
  CTA_BANCO VARCHAR(30),
  CLABE_INTERBANCARIA VARCHAR(40),
  TIPO_DE_BENIFICIARIO VARCHAR(60),
  NUM_CONTRATO VARCHAR(30),
  SOLICITUD_DE_EMPLEO BOOLEAN,
  PADRON_GOBIERNO_DEL_ESTADO BOOLEAN,
  CV BOOLEAN,
  ACREDITACIONES_CONSTANCIAS BOOLEAN,
  CEDULA_PROFESIONAL BOOLEAN,
  NUMERO_CEDULA_PROFESIONAL VARCHAR(20),
  TITULO_PROFESIONAL BOOLEAN,
  INE BOOLEAN,
  CURP2 BOOLEAN,
  ACTA_DE_NACIMIENTO BOOLEAN,
  COMPROBANTE_DE_DOMICILIO BOOLEAN,
  CONSTANCIA_DEL_SAT BOOLEAN,
  NO_INHABILITADO BOOLEAN,
  ANTECEDENTES_NO_PENALES BOOLEAN,
  CERTIFICADO_MEDICO BOOLEAN,
  CARTA_DE_RECOMENDACION BOOLEAN,
  CARTA_DE_RECOMENDACION2 BOOLEAN,
  CARATULA_BANCARIO BOOLEAN,
  FOTOGRAFIA_TAMAÑO_INFANTIL BOOLEAN,
  LICENCIA_PARA_CONDUCIR BOOLEAN,
  PADRON_GOBIERNO_DEL_ESTADO2 VARCHAR(50),
  ACTA_CONSTITUTIVA VARCHAR(50),
  CONSTANCIA_DEL_SAT2 VARCHAR(50),
  OPINION_POSITIVA VARCHAR(50),
  COMPROBANTE_DE_DOMICILIO2 VARCHAR(50),
  SEMBLANZA_CURRICULAR_PM VARCHAR(50),
  CARATULA_BANCARIO2 VARCHAR(50),
  CV_RL VARCHAR(50),
  INE_RL VARCHAR(50),
  CEDULA_PROFESIONAL_RL VARCHAR(50),
  NUMERO_CEDULA_PROFESIONAL_RL VARCHAR(50),
  CURP_RL VARCHAR(50),
  ACTA_DE_NACIMIENTO_RL VARCHAR(50),
  PRIMARY KEY (id)
);

